CourseSystem/Controllers/DashboardController.cs
using System.Security.Claims;
using CourseSystem.Data;
using CourseSystem.Models;
using CourseSystem.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CourseSystem.Controllers;

public class DashboardController : Controller
{
    private readonly UserManager<ApplicationUser> _userManager;

    private readonly ApplicationDbContext _context;
    
    public DashboardController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
    {
        _userManager = userManager;
        _context = context;
    }

    private List<CourseViewModel>? GetTeacherCourses(string userId)
    {
        var courses = _context.TeacherCourses
            .Where(tt => tt.TeacherId == userId)
            .Join(_context.CourseGrades,
                tt => tt.CourseGradeId,
                cs => cs.Id,
                (tt, cs) => new { CourseSinif = cs, TeacherTeaches = tt })
            .Join(_context.Courses,
                cs => cs.CourseSinif.CourseId,
                c => c.Id,
                (cs, c) => new { CourseSinif = cs.CourseSinif, Course = c })
            .Join(_context.Grades,
                cc => cc.CourseSinif.GradeId,
                s => s.Id,
                (cc, s) => new { CourseSinif = cc.CourseSinif, Course = cc.Course, Sinif = s })
            .Select(ccs => new CourseViewModel {
                Course = ccs.Course,
                GradeName = ccs.Sinif.Name
            })
            .ToList();
        
        return courses;
    }
    private List<CourseViewModel>? GetStudentCourses(Guid? gradeId)
    {
        if (gradeId == null)
        {
            return null;
        }
        var courses = _context.CourseGrades
            .Where(cs => cs.GradeId == gradeId)
            .Join(_context.Courses,
                cs => cs.CourseId,
                c => c.Id,
                (cs, c) => new { CourseSinif = cs, Course = c })
            .Join(_context.Grades,
                ccs => ccs.CourseSinif.GradeId,
                s => s.Id,
                (ccs, s) => new { CourseSinif = ccs.CourseSinif, Course = ccs.Course, Sinif = s })
            .Select(ccs => new CourseViewModel() {
                Course = ccs.Course,
                GradeName = ccs.Sinif.Name
            })
            .ToList();
        
        return courses;
    }

    private List<Content> GetTeacherLectures(Guid id)
    {
        var lectures = _context.CourseContents.Where(c => c.CourseId == id)
            .Join(_context.Contents, cc => cc.ContentId,
                ct => ct.Id, (cc, ct) => ct).ToList();
        return lectures;
    }
    private List<Content> GetStudentLectures(Guid id)
    {
        var homeworks = _context.CourseContents.Where(c => c.CourseId == id)
            .Join(_context.Contents, cc => cc.ContentId,
                ct => ct.Id, (cc, ct) => ct).Where(ct => ct.IsHomework == true).ToList();
        return homeworks;
    }

    public async Task<IActionResult> Index()
    {
        var courses = new List<CourseViewModel>();
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var user = await _userManager.FindByIdAsync(userId);
        
        var userRoles = await _userManager.GetRolesAsync(user);
        if (userRoles.Contains("Teacher"))
        {
            courses = GetTeacherCourses(userId);
        }

        if (userRoles.Contains("Student"))
        {
            courses = GetStudentCourses(user.GradeId);
        }
        
        return View("Dashboard",courses);
    }
    
    public async Task<IActionResult> Lectures(Guid id)
    {
        var lectures = new List<Content>();
    
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var user = await _userManager.FindByIdAsync(userId);
    
        var userRoles = await _userManager.GetRolesAsync(user);

        if (userRoles.Contains("Teacher"))
        {
            ViewBag.courses = GetTeacherCourses(userId);
            lectures = GetTeacherLectures(id);
        }

        if (userRoles.Contains("Student"))
        {
            ViewBag.courses = GetStudentCourses(user.GradeId);
            lectures = GetStudentLectures(id);
        }

        return View("Lectures", lectures);
    }

}

CourseSystem/Controllers/TeacherCourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseSystem.Data;
using CourseSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace CourseSystem.Controllers
{
    [Authorize(Roles = "Admin, SuperAdmin")]

    public class TeacherCourseController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public TeacherCourseController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: TeacherCourse
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.TeacherCourses.Include(t => t.CourseGrade).Include(t => t.Teacher);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: TeacherCourse/Details/5
        public async Task<IActionResult> Details(string? teacherId, Guid? courseGradeId)
        {
            if (teacherId == null || courseGradeId == null  || _context.TeacherCourses == null)
            {
                return NotFound();
            }

            var teacherTeach = await _context.TeacherCourses.FindAsync(teacherId, courseGradeId);
            if (teacherTeach == null)
            {
                return NotFound();
            }

            return View(teacherTeach);
        }

        // GET: TeacherCourse/Create
        public IActionResult Create()
        {
            ViewData["CourseGradeId"] = new SelectList(_context.CourseGrades, "Id", "CourseGradeName");
            ViewData["TeacherId"] = new SelectList( _userManager.GetUsersInRoleAsync("Teacher").Result, "Id", "FullName");
            return View();
        }

        // POST: TeacherCourse/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeacherId,CourseGradeId")] TeacherCourse teacherCourse)
        {
            if (ModelState.IsValid)
            {
                if (!TeacherTeachExists(teacherCourse.TeacherId, teacherCourse.CourseGradeId))
                {
                    _context.Add(teacherCourse);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError(string.Empty, "A duplicate entry already exists.");
            }
            ViewData["CourseGradeId"] = new SelectList(_context.CourseGrades, "Id", "Id", teacherCourse.CourseGradeId);
            ViewData["TeacherId"] = new SelectList(_context.Users, "Id", "FullName", teacherCourse.TeacherId);
            return View(teacherCourse);
        }

        // GET: TeacherCourse/Edit/5
        public async Task<IActionResult> Edit(string teacherId, Guid courseGradeId)
        {
            if (teacherId == null || _context.TeacherCourses == null)
            {
                return NotFound();
            }

            var teacherTeach = await _context.TeacherCourses.FindAsync(teacherId, courseGradeId);
            if (teacherTeach == null)
            {
                return NotFound();
            }
            ViewData["CourseGradeId"] = new SelectList(_context.CourseGrades, "Id", "CourseGradeName", teacherTeach.CourseGradeId);
            ViewData["TeacherId"] = new SelectList(_context.Users, "Id", "FullName", teacherTeach.TeacherId);
            return View(teacherTeach);
        }

        // POST: TeacherCourse/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string teacherId,Guid courseGradeId, [Bind("TeacherId,CourseGradeId")] TeacherCourse teacherCourse)
        {
            if (teacherId != teacherCourse.TeacherId || courseGradeId != teacherCourse.CourseGradeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (!TeacherTeachExists(teacherCourse.TeacherId, teacherCourse.CourseGradeId))
                {
                    try
                    {
                        _context.Update(teacherCourse);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!TeacherTeachExists(teacherCourse.TeacherId, teacherCourse.CourseGradeId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError(string.Empty, "A duplicate entry already exists.");
            }
            ViewData["CourseGradeId"] = new SelectList(_context.CourseGrades, "Id", "CourseGradeName", teacherCourse.CourseGradeId);
            ViewData["TeacherId"] = new SelectList(_context.Users, "Id", "FullName", teacherCourse.TeacherId);
            return View(teacherCourse);
        } 
        public async Task<IActionResult> DeleteConfirmed(string teacherId, Guid courseGradeId)
        {
            if (_context.TeacherCourses == null)
            {
                return Json(new { silindimi = false, hataMesaji = "Entity set 'ApplicationDbContext.TeacherCourses'  is null." });
            }
            var teacherTeach = await _context.TeacherCourses.FindAsync(teacherId, courseGradeId);
            if (teacherTeach != null)
            {
                _context.TeacherCourses.Remove(teacherTeach);
            }
            
            await _context.SaveChangesAsync();
            return Json(new { silindimi = true });
        } 
        private bool TeacherTeachExists(string teacherId, Guid courseGradeId)
        {
          return (_context.TeacherCourses?.Any(e => e.TeacherId == teacherId && e.CourseGradeId == courseGradeId)).GetValueOrDefault();
        }
    }
}

CourseSystem/Views/Shared/_LayoutTeacher.cshtml
<!DOCTYPE html>
<html lang="tr">

<!-- Mirrored from educhamp.themetrades.com/demo/admin/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 22 Feb 2019 13:08:15 GMT -->
<head>

    <!-- META ============================================= -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="" />
    <meta name="robotikbilim" content="" />
    <meta name="egt" content="" />

    <!-- FAVICONS ICON ============================================= -->
    <link rel="icon" href="../error-404.html" type="image/x-icon" asp-append-version="true" />
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/images/logoicon.png" asp-append-version="true" />

    <!-- PAGE TITLE HERE ============================================= -->
    <title>Robotik Bilim</title>

    <!-- MOBILE SPECIFIC ============================================= -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--[if lt IE 9]>
    <script src="~/Scripts/js/html5shiv.min.js"></script>
    <script src="~/Scripts/js/respond.min.js"></script>
    <![endif]-->
    <!-- All PLUGINS CSS ============================================= -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/assets.css" asp-append-version="true">
    <link rel="stylesheet" type="text/css" href="~/Content/vendors/calendar/fullcalendar.css" asp-append-version="true">

    <!-- TYPOGRAPHY ============================================= -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/typography.css" asp-append-version="true">

    <!-- SHORTCODES ============================================= -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/shortcodes/shortcodes.css" asp-append-version="true">

    <!-- STYLESHEETS ============================================= -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/style.css" asp-append-version="true">
    <link rel="stylesheet" type="text/css" href="~/Content/css/dashboard.css" asp-append-version="true">
    <link class="skin" rel="stylesheet" type="text/css" href="~/Content/css/color/color-1.css" asp-append-version="true">

</head>
<body class="ttr-opened-sidebar ttr-pinned-sidebar">

    <!-- header start -->
    <!-- header end -->
    <!-- Left sidebar menu start -->
    <!-- Left sidebar menu end -->

    <header class="ttr-header">
        <div class="ttr-header-wrapper">
            <!--sidebar menu toggler start -->
            <div class="ttr-toggle-sidebar ttr-material-button">
                <i class="ti-close ttr-open-icon"></i>
                <i class="ti-menu ttr-close-icon"></i>
            </div>
            <!--sidebar menu toggler end -->
            <!--logo start -->
            <div class="ttr-logo-box">
                <div>
                    <a href="@Url.Action("Index","TeacherCourse")" class="ttr-logo">
                        <img class="ttr-logo-mobile" alt="" src="~/Content/images/logoicon.png" width="30" height="30">
                        <img class="ttr-logo-desktop" alt="" src="~/Content/images/yazilogoicon.png" width="160" height="27">
                    </a>
                </div>
            </div>
            <!--logo end -->
            <div class="ttr-header-menu">
                <!-- header left menu start -->
                <ul class="ttr-header-navigation">
                    <li>
                        <a href="@Url.Action("Index","TeacherCourse")" class="ttr-material-button ttr-submenu-toggle">HOME</a>
                    </li>

                </ul>
                <!-- header left menu end -->
            </div>
            <div class="ttr-header-right ttr-with-seperator">
                <!-- header right menu start -->
                <ul class="ttr-header-navigation">
                    <li>
                        <a href="#" class="ttr-material-button ttr-search-toggle"><i class="fa fa-search"></i></a>
                    </li>

                    <li>
                        <a href="#" class="ttr-material-button ttr-submenu-toggle"><span class="ttr-icon"><i class="ti-user"></i><width ="32px" height="32"></span></a>
                        <div class="ttr-header-submenu">
                            <ul>

                                <li><a href="@Url.Action("Login","Home")">Logout</a></li>
                            </ul>
                        </div>
                    </li>

                </ul>
                <!-- header right menu end -->
            </div>
            <!--header search panel start -->
            <div class="ttr-search-bar">
                <form class="ttr-search-form">
                    <div class="ttr-search-input-wrapper">
                        <input type="text" name="qq" placeholder="search something..." class="ttr-search-input">
                        <button type="submit" name="search" class="ttr-search-submit"><i class="ti-arrow-right"></i></button>
                    </div>
                    <span class="ttr-search-close ttr-search-toggle">
                        <i class="ti-close"></i>
                    </span>
                </form>
            </div>
            <!--header search panel end -->
        </div>
    </header>
    <div class="ttr-sidebar">
        <div class="ttr-sidebar-wrapper content-scroll">
            <!-- side menu logo start -->
            <div class="ttr-sidebar-logo">
                <a href="@Url.Action("Index","TeacherCourse")"><img alt="" src="~/Content/images/yazilogoicon.png" width="122" height="27"></a>
                <!-- <div class="ttr-sidebar-pin-button" title="Pin/Unpin Menu">
                    <i class="material-icons ttr-fixed-icon">gps_fixed</i>
                    <i class="material-icons ttr-not-fixed-icon">gps_not_fixed</i>
                </div> -->
                <div class="ttr-sidebar-toggle-button">
                    <i class="ti-arrow-left"></i>
                </div>
            </div>

            <!-- side menu logo end -->
            <!-- sidebar menu start -->
            <nav class="ttr-sidebar-navi">
                <ul>


                    <li>
                        <a href="`#" class="ttr-material-button">
                            <span class="ttr-icon"><i class="ti-book"></i></span>
                            <span class="ttr-label">1.Sınıf Dersleri </span>
                            <span class="ttr-arrow-icon"><i class="fa fa-angle-down"></i></span>
                        </a>
                        <ul>
                            <li>
                                <a href="@Url.Action("LessonPage","Home")" class="ttr-material-button"><span class="ttr-label">Scratch</span></a>
                            </li>
                        </ul>
                    </li>


                    <li class="ttr-seperate"></li>
                </ul>
                <!-- sidebar menu end -->
            </nav>
            <!-- sidebar menu end -->
        </div>
    </div>

    @RenderBody()
    <div class="ttr-overlay"></div>

    <!-- External JavaScripts -->
    <script src="~/Scripts/js/jquery.min.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/bootstrap/js/popper.min.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/bootstrap/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/bootstrap-select/bootstrap-select.min.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/bootstrap-touchspin/jquery.bootstrap-touchspin.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/magnific-popup/magnific-popup.js"asp-append-version="true"></script>
    <script src="~/Content/vendors/counter/waypoints-min.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/counter/counterup.min.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/imagesloaded/imagesloaded.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/masonry/masonry.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/masonry/filter.js"asp-append-version="true"></script>
    <script src="~/Content/vendors/owl-carousel/owl.carousel.js" asp-append-version="true"></script>
    <script src='~/Content/vendors/scroll/scrollbar.min.js' asp-append-version="true"></script>
    <script src="~/Scripts/js/functions.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/chart/chart.min.js" asp-append-version="true"></script>
    <script src="~/Scripts/js/admin.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/summernote/summernote.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/file-upload/imageuploadify.min.js" asp-append-version="true"></script>
    <script src="~/Content/vendors/switcher/switcher.js" asp-append-version="true"></script>
    <script src='~/Content/vendors/calendar/moment.min.js' asp-append-version="true"></script>
    <script src='~/Content/vendors/calendar/fullcalendar.js' asp-append-version="true"></script>

    <script>
        $(document).ready(function () {

            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay,listWeek'
                },
                defaultDate: '2019-03-12',
                navLinks: true, // can click day/week names to navigate views

                weekNumbers: true,
                weekNumbersWithinDays: true,
                weekNumberCalculation: 'ISO',

                editable: true,
                eventLimit: true, // allow "more" link when too many events
                events: [
                    {
                        title: 'All Day Event',
                        start: '2019-03-01'
                    },
                    {
                        title: 'Long Event',
                        start: '2019-03-07',
                        end: '2019-03-10'
                    },
                    {
                        id: 999,
                        title: 'Repeating Event',
                        start: '2019-03-09T16:00:00'
                    },
                    {
                        id: 999,
                        title: 'Repeating Event',
                        start: '2019-03-16T16:00:00'
                    },
                    {
                        title: 'Conference',
                        start: '2019-03-11',
                        end: '2019-03-13'
                    },
                    {
                        title: 'Meeting',
                        start: '2019-03-12T10:30:00',
                        end: '2019-03-12T12:30:00'
                    },
                    {
                        title: 'Lunch',
                        start: '2019-03-12T12:00:00'
                    },
                    {
                        title: 'Meeting',
                        start: '2019-03-12T14:30:00'
                    },
                    {
                        title: 'Happy Hour',
                        start: '2019-03-12T17:30:00'
                    },
                    {
                        title: 'Dinner',
                        start: '2019-03-12T20:00:00'
                    },
                    {
                        title: 'Birthday Party',
                        start: '2019-03-13T07:00:00'
                    },
                    {
                        title: 'Click for Google',
                        url: 'http://google.com/',
                        start: '2019-03-28'
                    }
                ]
            });

        });</script>
</body>

<!-- Mirrored from educhamp.themetrades.com/demo/admin/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 22 Feb 2019 13:09:05 GMT -->
</html>

CourseSystem/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
        <!-- META ============================================= -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="keywords" content="" />
        <meta name="author" content="" />
        <meta name="robots" content="" />

        <!-- FAVICONS ICON ============================================= -->
        <link rel="icon" href="~/Content/images/favicon.ico" type="image/x-icon" />
        <link rel="shortcut icon" type="image/x-icon" href="~/Content/images/logoicon.png" />

        <!-- PAGE TITLE HERE ============================================= -->
        <title>Robotik Bilim </title>

        <!-- MOBILE SPECIFIC ============================================= -->
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!--[if lt IE 9]>
    <script src="~/Scripts/js/html5shiv.min.js"></script>
    <script src="~/Scripts/js/respond.min.js"></script>
    <![endif]-->
        <!-- All PLUGINS CSS ============================================= -->
        <link rel="stylesheet" type="text/css" href="~/Content/css/assets.css">

        <!-- TYPOGRAPHY ============================================= -->
        <link rel="stylesheet" type="text/css" href="~/Content/css/typography.css">

        <!-- SHORTCODES ============================================= -->
        <link rel="stylesheet" type="text/css" href="~/Content/css/shortcodes/shortcodes.css">

        <!-- STYLESHEETS ============================================= -->
        <link rel="stylesheet" type="text/css" href="~/Content/css/style.css">
        <link class="skin" rel="stylesheet" type="text/css" href="~/Content/css/color/color-1.css">

    </head>
<body>
    @RenderBody()
    <script src="~/Scripts/js/jquery.min.js"></script>
    <script src="~/Content/vendors/bootstrap/js/popper.min.js"></script>
    <script src="~/Content/vendors/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/vendors/bootstrap-select/bootstrap-select.min.js"></script>
    <script src="~/Content/vendors/bootstrap-touchspin/jquery.bootstrap-touchspin.js"></script>
    <script src="~/Content/vendors/magnific-popup/magnific-popup.js"></script>
    <script src="~/Content/vendors/counter/waypoints-min.js"></script>
    <script src="~/Content/vendors/counter/counterup.min.js"></script>
    <script src="~/Content/vendors/imagesloaded/imagesloaded.js"></script>
    <script src="~/Content/vendors/masonry/masonry.js"></script>
    <script src="~/Content/vendors/masonry/filter.js"></script>
    <script src="~/Content/vendors/owl-carousel/owl.carousel.js"></script>
    <script src="~/Content/vendors/scroll/scrollbar.min.js"></script>
    <script src="~/Scripts/js/functions.js"></script>
    <script src="~/Scripts/js/admin.js"></script>
    <script src="~/Scripts/js/contact.js"></script>
</body>
</html>